# Generated by Django 4.2.6 on 2023-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boolmodel_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool1', models.BooleanField()),
                ('bool2', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Charfield_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char1', models.CharField(max_length=20)),
                ('char2', models.EmailField(max_length=254)),
                ('char3', models.GenericIPAddressField()),
                ('char4', models.SlugField()),
                ('char5', models.TextField(max_length=100)),
                ('char6', models.JSONField()),
                ('char7', models.URLField()),
                ('char8', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='datafield_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('date2', models.TimeField()),
                ('data3', models.DateTimeField()),
                ('date4', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='filemodels_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Numfield_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.PositiveSmallIntegerField()),
                ('num3', models.PositiveBigIntegerField()),
                ('num4', models.SmallIntegerField()),
                ('num5', models.BigIntegerField()),
                ('num6', models.DecimalField(decimal_places=3, max_digits=5)),
                ('num7', models.FloatField()),
                ('num8', models.GenericIPAddressField()),
                ('num9', models.PositiveIntegerField()),
            ],
        ),
    ]
