# Generated by Django 4.2.6 on 2023-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_constraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constraints',
            old_name='subject',
            new_name='c_subject',
        ),
        migrations.AlterField(
            model_name='constraints',
            name='ID',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='email',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
